name: Cent OS Build (OpenSSL 1.1.1)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: docker build . --file docker/centos7.dockerfile --tag zipsign:$(date +%s)
