name: Mac OS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install openssl cmake googletest

      - name: Configure
        run: |
          cmake -B build

      - name: Build
        run: |
          cmake --build build

      - name: Unit Test
        run: |
          cmake --build build --target test

#      - name: Memcheck
#        working-directory: build
#        run: |
#          valgrind --error-exitcode=1 ./alltests

