name: Mac OS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 17 * * 5'

jobs:

  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: brew install openssl cmake googletest

      - name: Configure
        run: |
          cmake -B build

      - name: Build
        run: |
          cmake --build build

      - name: Unit Test
        run: |
          cmake --build build --target test
